---
- name: include configure_ceph_command_aliases.yml
  include_tasks: configure_ceph_command_aliases.yml

- name: wait for monitor socket to exist
  command: "{{ docker_exec_cmd }} sh -c 'stat /var/run/ceph/{{ cluster }}-mon.{{ ansible_hostname }}.asok || stat /var/run/ceph/{{ cluster }}-mon.{{ ansible_fqdn }}.asok'"
  changed_when: false
  register: monitor_socket
  retries: 5
  delay: 15
  until: monitor_socket.rc == 0

- name: force peer addition as potential bootstrap peer for cluster bringup
  command: "{{ docker_exec_cmd }} ceph --admin-daemon /var/run/ceph/{{ cluster }}-mon.{{ monitor_name }}.asok add_bootstrap_peer_hint {{ _current_monitor_address }}"
  changed_when: false
  failed_when: false
  when:
    - not containerized_deployment_with_kv
