---
- name: waiting for the monitor(s) to form the quorum...
  command: >
    {{ docker_exec_cmd }}
    ceph
    --cluster {{ cluster }}
    -n mon.
    -k /var/lib/ceph/mon/{{ cluster }}-{{ ansible_hostname }}/keyring
    mon_status
    --format json
  register: ceph_health_raw
  until: >
    (ceph_health_raw.stdout | from_json)['state'] in ['leader', 'peon']
  retries: "{{ handler_health_mon_check_retries }}"
  delay: "{{ handler_health_mon_check_delay }}"
  when:
    - ceph_release_num[ceph_release] >= ceph_release_num.nautilus

- name: fetch ceph keys
  ceph_key:
    state: fetch_initial_keys
    cluster: "{{ cluster }}"
  when:
    - cephx

- name: create ceph mgr keyring(s)
  ceph_key:
    name: "mgr.{{ hostvars[item]['ansible_hostname'] }}"
    state: present
    caps:
      mon: allow profile mgr
      osd: allow *
      mds: allow *
    cluster: "{{ cluster }}"
    secret: "{{ (mgr_secret != 'mgr_secret') | ternary(mgr_secret, omit) }}"
  environment:
    CEPH_CONTAINER_IMAGE: "{{ ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag if containerized_deployment else None }}"
  when:
    - cephx
    - inventory_hostname == groups[mon_group_name]|last
  with_items:
    - "{{ groups.get(mgr_group_name, []) }}" # this honors the condition where mgrs run on separate machines
    - "{{ groups.get(mon_group_name, []) }}" # this honors the new rule where mgrs are always collocated with mons

# once this gets backported github.com/ceph/ceph/pull/20983
# we will be able to remove these 2 tasks below
- name: find ceph keys
  shell: ls -1 /etc/ceph/*.keyring
  changed_when: false
  register: ceph_keys
  check_mode: no
  when:
    - cephx

- name: set keys permissions
  file:
    path: "{{ item }}"
    owner: "ceph"
    group: "ceph"
    mode: "{{ ceph_keyring_permissions }}"
  with_items:
    - "{{ ceph_keys.get('stdout_lines') | default([]) }}"
  when:
    - cephx

- name: copy keys to the ansible server
  fetch:
    src: "{{ item }}"
    dest: "{{ fetch_directory }}/{{ fsid }}/{{ item }}"
    flat: yes
  with_items:
    - "{{ ceph_keys.get('stdout_lines') | default([]) }}"
    - /var/lib/ceph/bootstrap-osd/{{ cluster }}.keyring
    - /var/lib/ceph/bootstrap-rgw/{{ cluster }}.keyring
    - /var/lib/ceph/bootstrap-mds/{{ cluster }}.keyring
    - /var/lib/ceph/bootstrap-rbd/{{ cluster }}.keyring
    - /var/lib/ceph/bootstrap-rbd-mirror/{{ cluster }}.keyring
  when:
    - cephx
    - inventory_hostname == groups[mon_group_name] | last
